name: build react project
on: push
jobs:
  npm-build:
    name: npm build work
    runs-on: ubuntu-latest
    steps:
      - name: read repo content
        uses: actions/checkout@v7

      - name: install dependencies and package
        run: |
          npm install
          npm run build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
          branch: gh-pages
        
