name: Inspect runner
on:
  push:
    branches:
      - tmp
  workflow_dispatch:


jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: Before checkout
        run: |
          echo "Before checkout"
          pwd
          ls -la
      - name: Checkout
        uses: actions/checkout@v7
      # This is a comment
      - name: After checkout
        run: |
          echo "After checkout"
          pwd
          ls -la

          git status
          git log --all --oneline --graph
          cat .git/HEAD
