name: Inspect runner
on:
  push:
    branches:
      - tmp
  workflow_dispatch:


jobs:
  inspect:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            label: Windows-x64

          - os: macos-15
            label: macOS-arm64

    runs-on: ${{matrix.os}}
    steps:
      - name: Print matrix
        run: |
          echo "matrix.os = ${{matrix.os}}"
          echo "runner.os = ${{runner.os}}"
        
