name: Inspect runner
on:
  push:
    branches:
      - tmp
  workflow_dispatch:


jobs:
  test:
   
    runs-on: ubuntu-latest
    env:
      MY_VALUE: "123"
      PYTHONUTF8: "1"
    steps:
      - name: Print matrix
        run: |
          echo "$MY_VALUE"          
          echo "$PYTHONUTF8"
      - name: Python see variables
        run: |
          python -c "import os; print(os.environ['MY_VALUE'])"
